### ISSUE TITLE
14.1 Question 1.7c, method 1 possible mistake

### ISSUE THREAD

**Issue by potusotis** [igorvanloo/Dummit-Foote-Chapter-14-Exercises#1]
Hi, I hope you're doing well. I do not see the claim of contradiction that x=σ(x) in 14.1, 1.7c, method 1. I believe the contradiction should arise from the fact that, when we choose q in the rational numbers, we have the liberty to choose that q is not be equal to σ(x), since Q is dense. Then q<x implies σ(q)<σ(x), i.e., q<σ(x). Then we have q<σ(x)<q which implies σ(x)=q, a contradiction. Let me know if I've made an oversight here, and I appreciate your contribution of these exercises! Have a good one.

**Comment by igorvanloo** [comment]
Hello! I see my mistake, I should've written "and therefore q = σ(x)"!

I think I meant to write the same thing as you but made a typo. If you could check my working below I'll edit :)

1. Suppose sigma is not the identity, then either x < σ(x) or x > σ(x)
2. Let x < σ(x) (reverse case is same proof)
3. Since Q is dense in R and s(x) is in R by part a, there is a q s.t x < q < σ(x)
4. By part b x < q implies σ(x) < σ(q)
5. Therefore we have x < q < σ(x) < σ(q) = q, that is q < σ(x) < q
6. We conclude that σ(x) = q, that is x = q, a contradiction

**Comment by potusotis** [comment]
I agree with all except the final statement; that "x=q, a contradiction". I might just not be seeing it, as it "feels" that if σ(x) = q, and since Q is fixed under σ, that this demands x=q... But how are we certain? The contradiction that follow most naturally to me is that, in step 3, when we pick q to be between x and σ(x), namely x<q<σ(x), we _really_ mean between; q is not equal to x, and q is not equal to σ(x). Then following through the steps, we arrive at σ(x) = q, which is a contradiction to our picking of q, which we know is possible from the denseness of Q. Let me know your train of thought (or proof) that x=q follows from σ(x) = q, and that it really is a contradiction -- I might just not be seeing it. I look forward to hearing your response!

**Comment by igorvanloo** [comment]
I understand your proof! For my case to me the fact that σ is a automorphism, namely an isomorphism which fixes Q ensures that if σ(x) = q then it must be that x = q by injectivity. Suppose x does not equal q, then we have σ(x) = q = σ(q) which implies that σ(x) - σ(q) = σ(x - q) = 0 which implies x - q = 0 which implies x = q. Does that seem correct to you?

**Comment by potusotis** [comment]
I see your path! Thanks for showing me that, I wasn't seeing it for some reason haha. Now we have two paths, beautiful!
